language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install -U setuptools==70.0.0 urllib3<2
  - pip install black flake8 coverage coveralls

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: "us-west-2"
  app: "swe1-app"
  env: "swe1-app-dev"
  bucket_name: "elasticbeanstalk-us-west-2-767828756778"
  on:
    branch: main
